### ISSUE TITLE
cgaify on Win10

### ISSUE THREAD

**Issue by lukas12p** [jhhoward/WolfensteinCGA#12]
Hi
cgaify.exe doesn't work on Windows 10. On what windows does it run?
![obraz](https://github.com/jhhoward/WolfensteinCGA/assets/9913232/d611cd25-0b35-4a22-bad4-c3fced80f491)

**Comment by jhhoward** [comment]
You will need a C++ compiler and compile cgaify.cpp found in the 'tools' directory.

If you have Visual Studio installed with the C++ tools, you can use the developer command prompt and simply compiler with:
`cl cgaify.cpp`
