### ISSUE TITLE
20% broken on Tandy 1400LT Laptop

### ISSUE THREAD

**Issue by zombienerd** [jhhoward/WolfensteinCGA#5]
The laptop has a "4 shades of blue" supertwist 640x200 CGA display, in a wide format.

Tried LCD and WIDE modes.  The game loads.  Menus are corrupt (instead of the pointer, I get a 4x scaled BJ, sometimes the OPTIONS text shows), and once in game, the HUD doesn't display properly.  Shooting my gun shows the credits page.  When exiting the game, I get garbled text (but am still able to interact with dos and restart the game, I think it's not re-initializing normal video mode)

Photo 1: LCD Startup
Photo 2: WIDE Startup
Photo 3, 4, 5: Menu corruption
Photo 6,7: Showing missing Hud
Photo 8: Showing screen after quitting

I could not capture a picture of the credits page while shooting, it just flashes too fast.

![LCD start](https://user-images.githubusercontent.com/15084770/214394858-50c0e7dd-c7dc-4862-ad81-36f654e56d2c.jpg)
![Wide start](https://user-images.githubusercontent.com/15084770/214394882-e6dc0a66-ba13-4801-94c2-30873bab737a.jpg)
![Menu Glitch 1](https://user-images.githubusercontent.com/15084770/214394918-7ce2c962-a3f3-4056-be12-ca31aa495853.jpg)
![Menu Glitch 2](https://user-images.githubusercontent.com/15084770/214394922-0a6008b4-efe5-4b75-8b8f-d71d653fa03e.jpg)
![Menu Glitch 3](https://user-images.githubusercontent.com/15084770/214394926-80f868e9-da89-400b-a60a-7578d6614163.jpg)
![No Hud1](https://user-images.githubusercontent.com/15084770/214394952-2a554b15-b04b-41b5-8f1b-318af204150f.jpg)
![No Hud2](https://user-images.githubusercontent.com/15084770/214394957-2bd30964-ec3a-422e-892e-e918b6044f45.jpg)
![After Quitting](https://user-images.githubusercontent.com/15084770/214394974-58e8d874-71a0-4927-a411-06a1fbae61d4.jpg)

**Comment by TheElf01** [comment]
Hi, happen same to me, but was wrong Wolfenstein version,  download this one

Wolfenstein 3D (1.4c) [Mindscape]


Works great

**Comment by zombienerd** [comment]
> Hi, happen same to me, but was wrong Wolfenstein version, download this one
> 
> Wolfenstein 3D (1.4c) [Mindscape]
> 
> Works great

I momentarily considered it might be a version mismatch that went awry with the conversion.  I'll give that a shot.  I was just working from the retail disks I have.  I forget what version it is lol.

**Comment by zombienerd** [comment]
Problem resolved.  It was a version issue.  Game now looks correct!  
![working 1](https://user-images.githubusercontent.com/15084770/214450912-f173c08f-4154-4428-8417-021bbca0a30f.jpg)
![working 2](https://user-images.githubusercontent.com/15084770/214450915-cc9a6357-17c1-4eac-b672-0a5e4cc461ea.jpg)
